sudo: required
dist: trusty

language: rust
rust:
  - nightly-2016-04-09

services:
  - postgresql

env:
  DATABASE_URL=postgres://postgres@localhost/pseudo_lang

before_script:
  - rustc -vV
  - cargo -vV
  - cargo install diesel_cli --verbose
  - export PATH=$PATH:/home/travis/.cargo/bin
  - diesel database setup
