language: rust
rust:
  - nightly-2016-04-09

services:
  - postgresql
  - sqlite3

env:
  DATABASE_URL=postgres://postgres@localhost/

before_script:
  - cargo install diesel_cli --verbose
  - diesel database setup
