language: rust
rust:
  - nightly-2016-04-09

services:
  - postgresql

env:
  DATABASE_URL=postgres://postgres@localhost/

before_script:
  - cargo install diesel_cli --verbose
  - diesel database setup

addons:
  apt:
    packages:
      - libsqlite3-dev
