sudo: required
dist: trusty

language: rust
rust:
  - nightly-2016-04-09

services:
  - postgresql

env:
  DATABASE_URL=postgres://postgres@localhost/pseudo_lang

before_script:
  - lsb_release -a
  - rustc --version
  - cargo --version
  - sudo apt-get -qq update
  - sqlite3 --version
  - sudo apt-get install --only-upgrade sqlite3 libsqlite3-dev
  - sqlite3 --version
  - cargo install diesel_cli --verbose
  - diesel database setup
