language: rust
rust:
  - nightly-2016-04-09

services:
  - postgresql

env:
  DATABASE_URL=postgres://postgres@localhost/pseudo_lang

before_script:
  - cargo --version
  - rustc --version
  - whoami
  - cargo install diesel_cli --verbose
  - diesel database setup
